### ISSUE TITLE
Oppo Plugin not recognised

### ISSUE THREAD

**Issue by mtate01** [carlosgamezvillegas/homebridge-plugin-oppo#1]
Hi,

I'm attempting to configure homebridge-pluging-oppo to work on a Raspbery Pi Homebridge server.  Server is up and functional with several functioning plug-ins, but when I try to load your Oppo plug-in, The Homebridge JSON throw the following error in the Homebridge console.  

"No plugin was found for the platform "oppoPlugin" in your config.json. Please make sure the corresponding plugin is installed correctly."

Any ideas on what might be the cause?

Thanks heaps!!

Marcus

**Comment by mtate01** [comment]
I managed to resolve the above problem by going to the Homebridge console, searching for the oppo plugin and installing it from there.  Somehow despite having installed with npm and correctly adding the config.json elements, it never registers when installed by npm directly.  Some missing step here maybe?

**Comment by carlosgamezvillegas** [comment]
Hello Marcus,

I’m glad to hear that is working. I will look into your suggestion to make sure it can be installed with npm. If you have any issues and suggestions please reach out. As of now, I am the only one testing the plug-in so any feedback would be appreciated. 

Kind regards,

carlos

**Comment by mtate01** [comment]
Hi Carlos.  I'm so happy to have a Homebridge plugin for my Oppo!  It was a missing link in my home automation set up.  I'll keep testing and let you know if I come up with anything.
All the best, 
Marcus
