### ISSUE TITLE
bridge not starting after update

### ISSUE THREAD

**Issue by hanses89** [carlosgamezvillegas/homebridge-plugin-oppo#3]
I get this after update.. has been working fine upon updating like 14 days ago:(

Any help would be much appriciated. 
![image](https://user-images.githubusercontent.com/62284780/177762833-3b362e49-96d3-4bc8-bd0f-d5d628d5e689.png)

**Comment by carlosgamezvillegas** [comment]
Hello Hanses,

can you send over more information logs, plug-in version, what operating system is hombridge running on?  I would like to see at what step the plugin is failing to load.

also, can you clarify if the plug-in cannot load after an Oppo plugin update or a homebridge update? If it is because of the Oppo plug-in update you can install the last version that was working for you.


Kind regards,

**Comment by hanses89** [comment]
9.7.2022, 18:57:45oppoudpbridge stopping
9.7.2022, 18:57:50Oppo Udp Bridge starting
9.7.2022, 18:57:53Oppo Udp BridgeLoaded plugin 'homebridge-oppo-udp'
9.7.2022, 18:57:53Oppo Udp BridgeLoading 1 platforms...
9.7.2022, 18:57:53Oppo Udp BridgeWARNINGunhandled rejection: TypeError: this.udpServer is not a function

This is what I get when trying to start the bridge. I'm running hoobs on a raspberry pi.

I'm
Running version 4.0.0 of the plug-in. I think there was a combined hoobs and plug-in update at the same time. But this plug-in was the only one that failed afterwards

**Comment by carlosgamezvillegas** [comment]
Hello Hans,

Please try the 4.0.1 update I just released. That should solve your issue.  Let me know if it works.

Thank you for reporting bugs in the code.

**Comment by hanses89** [comment]
For some reason I don't see it in the library in hoobs!? But I can see it at nmpjs..

**Comment by hanses89** [comment]
Any idea?:)

**Comment by carlosgamezvillegas** [comment]
Hello Hans,

I don’t know why it is not showing up in Hoobs, like you said it shows up in nmpjs.  

We have 3 different options here to get it working:

1. Wait for Hoobs to update the library.
2. Ask Hoobs why the new update is not showing up, probably there is something on my end that I need to fix.
3. Installed the previous version of the plug-in that was working for you.

Let me see if you try on if those ideas


Kind regards,

**Comment by hanses89** [comment]
Here is the reply from hoobs:

The developer needs to update his github plugin, even on the site you sent me it shows his Repository at the github site

**Comment by hanses89** [comment]
So basicaly not much:)

**Comment by carlosgamezvillegas** [comment]
Hello Hans,

Thank you for reaching out to Hoobs.  I will update the plugin in GitHub and let you know when I am done. I was not aware the Hoobs uses GitHub to refresh their directory, I have only used Hombridge UIX and it uses nmpjs to refresh the plugins. 

Kind regards,

**Comment by hanses89** [comment]
Ok! That makes sense! Thanks!:)
Let's hope the update fixes my problem as well ;)

**Comment by carlosgamezvillegas** [comment]
I updated the files in Github, let me know if it works.

**Comment by hanses89** [comment]
Still the same error:/

**Comment by hanses89** [comment]
Sorted it out after reinstalling the bridge:) thanks!

**Comment by hanses89** [comment]
Now I get this though:

2.7.2022, 18:59:34Oppo Udp BridgeOppo UDP-203IP not set yet

But the ip is set🙈

**Comment by carlosgamezvillegas** [comment]
Hello Hans,

The main change in this version is that the plug-in can find the IP automatically. The default option is. to search for the IP automatically but usually requieres some time (5 min) and the device to be on to find it. You might have the IP address set from the previous version but the option in settings “Set IP address manually”  might not be checked.  Please enable that option and let me know you still have the issue.
