### ISSUE TITLE
No name for switches in homekit

### ISSUE THREAD

**Issue by hanses89** [carlosgamezvillegas/homebridge-plugin-oppo#4]
Hi,

I can see the name of the switches in homebridge, but in homekit i only get unnamed switches, so it is impossible to see which one is which...

**Comment by carlosgamezvillegas** [comment]
Hello Hans,

I have had this issues with other Homebridge plug-ins as well so I am not sure if the issue is with HomeKit, Hombridge, or the plug-in itself. However, I have found out a work around the issue. If you go and try to rename each switch individual the name of the switch will appear. In order to get the name of the switch the “Switch” name needs to be deleted completely and rename it based on the grayed out name it has (see the image below.  Let me know if this workaround works for you.

![1AC52C8F-0824-432E-B420-C621E923B07F](https://user-images.githubusercontent.com/67111609/199268409-f3c6573b-0ecc-46a0-b6ab-721641c4df91.png)


Kind regards,

Carlos Gamez

**Comment by hanses89** [comment]
That did the trick! Thanks!
Any way to reorder the switches?


Mvh
Hans Erik
________________________________
Fra: carlosgamezvillegas ***@***.***>
Sendt: Tuesday, November 1, 2022 4:16:38 PM
Til: carlosgamezvillegas/homebridge-plugin-oppo ***@***.***>
Kopi: Hans Erik Sæbø ***@***.***>; Author ***@***.***>
Emne: Re: [carlosgamezvillegas/homebridge-plugin-oppo] No name for switches in homekit (Issue #4)


Hello Hans,

I have had this issues with other Homebridge plug-ins as well so I am not sure if the issue is with HomeKit, Hombridge, or the plug-in itself. However, I have found out a work around the issue. If you go and try to rename each switch individual the name of the switch will appear. In order to get the name of the switch the “Switch” name needs to be deleted completely and rename it based on the grayed out name it has (see the image below. Let me know if this workaround works for you.

[1AC52C8F-0824-432E-B420-C621E923B07F]<https://user-images.githubusercontent.com/67111609/199268409-f3c6573b-0ecc-46a0-b6ab-721641c4df91.png>

Kind regards,

Carlos Gamez

**Comment by hanses89** [comment]
No wait! It worked for another plug-in. But for oppo it worked when I go into the separate switches, but looking at the top level the switches still look like this

Mvh
Hans Erik
________________________________
Fra: Hans Erik Sæbø ***@***.***>
Sendt: Tuesday, November 1, 2022 5:23:44 PM
Til: carlosgamezvillegas/homebridge-plugin-oppo ***@***.***>; carlosgamezvillegas/homebridge-plugin-oppo ***@***.***>
Kopi: Author ***@***.***>
Emne: Re: [carlosgamezvillegas/homebridge-plugin-oppo] No name for switches in homekit (Issue #4)

That did the trick! Thanks!
Any way to reorder the switches?


Mvh
Hans Erik
________________________________
Fra: carlosgamezvillegas ***@***.***>
Sendt: Tuesday, November 1, 2022 4:16:38 PM
Til: carlosgamezvillegas/homebridge-plugin-oppo ***@***.***>
Kopi: Hans Erik Sæbø ***@***.***>; Author ***@***.***>
Emne: Re: [carlosgamezvillegas/homebridge-plugin-oppo] No name for switches in homekit (Issue #4)


Hello Hans,

I have had this issues with other Homebridge plug-ins as well so I am not sure if the issue is with HomeKit, Hombridge, or the plug-in itself. However, I have found out a work around the issue. If you go and try to rename each switch individual the name of the switch will appear. In order to get the name of the switch the “Switch” name needs to be deleted completely and rename it based on the grayed out name it has (see the image below. Let me know if this workaround works for you.

[1AC52C8F-0824-432E-B420-C621E923B07F]<https://user-images.githubusercontent.com/67111609/199268409-f3c6573b-0ecc-46a0-b6ab-721641c4df91.png>

Kind regards,

Carlos Gamez

**Comment by carlosgamezvillegas** [comment]
Hello Hans,

I have noticed this also, when I have Movie Progress, Chapter Number, and Chapter Progress enabled at the same time the name of every single switch/dimmer disappears from the top level view. When I use 2 out of the 3 the problem goes away (see picture below) but I don’t know if I add more switches the problem returns. Again, I don’t know if this is a HomeKit, Hombridge, or plug-in issue, I just know that it happens with other plug-ins like the Nest plug-in (see image below)

![47FD3E67-4F6C-4CC7-81FB-CC8B1D507D87](https://user-images.githubusercontent.com/67111609/199295829-eab25348-9190-4a21-adaa-5673edc8717b.png)
![ABB00880-AD68-4BA5-81CD-12439094ED33](https://user-images.githubusercontent.com/67111609/199295842-9427c218-c3d6-4213-8c9c-a54a4f7abe65.png)
![363AA594-79CF-489D-8283-9F15D74A5CD4](https://user-images.githubusercontent.com/67111609/199295849-abde986b-8c95-40a3-8ed6-4fd1e920486c.png)

Kind regards,

Carlos Gamez

**Comment by hanses89** [comment]
Had to remove a bunch! But is there a way to reorder the buttons?

Mvh
Hans Erik
________________________________
Fra: carlosgamezvillegas ***@***.***>
Sendt: Tuesday, November 1, 2022 6:18:33 PM
Til: carlosgamezvillegas/homebridge-plugin-oppo ***@***.***>
Kopi: Hans Erik Sæbø ***@***.***>; Author ***@***.***>
Emne: Re: [carlosgamezvillegas/homebridge-plugin-oppo] No name for switches in homekit (Issue #4)


Hello Hans,

I have noticed this also, when I have Movie Progress, Chapter Number, and Chapter Progress enabled at the same time the name of every single switch/dimmer disappears from the top level view. When I use 2 out of the 3 the problem goes away (see picture below) but I don’t know if I add more switches the problem returns. Again, I don’t know if this is a HomeKit, Hombridge, or plug-in issue, I just know that it happens with other plug-ins like the Nest plug-in (see image below)

[47FD3E67-4F6C-4CC7-81FB-CC8B1D507D87]<https://user-images.githubusercontent.com/67111609/199295829-eab25348-9190-4a21-adaa-5673edc8717b.png>
[ABB00880-AD68-4BA5-81CD-12439094ED33]<https://user-images.githubusercontent.com/67111609/199295842-9427c218-c3d6-4213-8c9c-a54a4f7abe65.png>
[363AA594-79CF-489D-8283-9F15D74A5CD4]<https://user-images.githubusercontent.com/67111609/199295849-abde986b-8c95-40a3-8ed6-4fd1e920486c.png>

Kind regards,

Carlos Gamez

**Comment by carlosgamezvillegas** [comment]
I think the buttons are ordered alphabetically by default by HomeKit and there is no way to reorder them right now. About the No button name issue, people have reported the issue with iOS 15 and 16 and I will send a bug report to apple about it.

I hope you are finding the Oppo plug-in and if you have any requests like adding other buttons/sensors let me know so we can discuss if it possible or not.

Kind regards, 

Carlos Gamez
